dist: xenial
sudo: required
language: python
services:
- docker
- mysql
before_script: mysql -uroot -e 'drop database if exists rnn_generator; create database rnn_generator;'
script: bash testDockerImage.sh
